export interface NursingTaskCategory {
  name: string;
  sort_order: number;
  items: string[];
}

export const CBU_NURSING_TASK_LIBRARY_SEED: NursingTaskCategory[] = [

  // ── SHARED: Getting Started ────────────────────────────────────────────────
  {
    name: 'CBU Nursing — Getting Started (All Plans)',
    sort_order: 300,
    items: [
      'Attend CBU orientation and meet with a pre-nursing academic advisor',
      'Declare pre-nursing major in Banner/CBU student portal',
      'Download and review the CBU College of Nursing Student Handbook',
      'Join the CBU Pre-Nursing Club or student nursing organization',
      'Set up CBU student email, Canvas (LMS), and Banner accounts',
      'Purchase a planner or use Daily Rhythm to track all deadlines',
      'Learn CBU Chapel attendance requirements and sign up',
      'Identify and meet your nursing academic advisor each semester',
      'Review the full list of BSN prerequisite courses and map them to your plan',
      'Research the difference between the 4-year, 4.5-year, and 5-year tracks',
      'Tour the CBU College of Nursing building and simulation labs',
      'Connect with current nursing students or CBU nursing alumni for guidance',
      'Set a GPA goal: aim for 3.5+ cumulative and 3.0+ science GPA minimum',
      'Research getting a CNA license — it strengthens your nursing application',
      'Look into volunteering at a local hospital or clinic for clinical hours',
      'Create an account on NursingCAS (used for BSN application)',
      'Save the CBU Nursing important dates page to your bookmarks',
    ],
  },

  // ── SHARED: Freshman Year ──────────────────────────────────────────────────
  {
    name: 'CBU Nursing — Freshman Year (All Plans)',
    sort_order: 301,
    items: [
      // Fall Semester
      'Fall: Enroll in ENG 113 (Composition) — required for BSN application',
      'Fall: Enroll in MAT 251 (Statistics) or equivalent math requirement',
      'Fall: Begin CHE 102 (Introductory Chemistry) if ready',
      'Fall: Complete CBU Christian Studies I (required for all students)',
      'Fall: Attend Chapel the required number of times per semester',
      'Fall: Meet with your academic advisor to confirm your semester plan',
      'Fall: Look into Peer Assisted Learning (PAL) tutoring for science classes',
      'Fall: Join a study group for chemistry and science prerequisite courses',
      // Spring Semester
      'Spring: Enroll in BIO 153 / 153L (Human Anatomy & Physiology I + Lab)',
      'Spring: Continue or complete CHE 102 if not finished in Fall',
      'Spring: Complete CBU Christian Studies II',
      'Spring: Explore volunteering at Riverside University Health System or local clinics',
      'Spring: Begin researching the TEAS exam — understand format and content',
      'Spring: Attend any nursing info sessions or open houses hosted by CBU College of Nursing',
      'Spring: Review your GPA at the end of the year — adjust study habits if needed',
      // Year-round
      'Shadow a nurse or healthcare professional for at least one day',
      'Research CNA (Certified Nursing Assistant) certification programs near Riverside',
      'Start a nursing journal — reflect on why you want to be a nurse',
    ],
  },

  // ── 4-YEAR PLAN ───────────────────────────────────────────────────────────
  {
    name: 'CBU Nursing — 4-Year Plan: Sophomore Year',
    sort_order: 310,
    items: [
      // Fall Sophomore
      'Fall: Enroll in BIO 163 / 163L (Human Anatomy & Physiology II + Lab)',
      'Fall: Enroll in CHE 112 / 112L (Organic & Biochemistry + Lab)',
      'Fall: Complete remaining general education requirements (social science, humanities)',
      'Fall: Begin TEAS exam preparation — purchase ATI TEAS study guide',
      'Fall: Maintain cumulative GPA of 3.0+ and science GPA of 2.8+',
      'Fall: Check NursingCAS application opening date for spring applicants',
      // Spring Sophomore
      'Spring: Enroll in BIO 205 / 205L (Human Microbiology + Lab)',
      'Spring: Complete any remaining prerequisite courses',
      'Spring: Take the TEAS exam — aim for 75%+ (competitive average is 78%)',
      'Spring: Open your NursingCAS application account',
      'Spring: Request letters of recommendation from science professors',
      'Spring: Write your nursing personal statement / essay',
      'Spring: Submit BSN application via NursingCAS before the deadline (typically Sept for Spring cohort)',
      'Spring: Submit all official transcripts through NursingCAS',
      'Spring: Track your BSN application status on NursingCAS',
      // Year
      'Earn CNA certification if not already done — strengthens application',
      'Volunteer at a hospital or care facility for at least 50 hours total',
      'Attend CBU Nursing application info sessions to understand selection process',
      'If applying for Spring cohort: note Fall application deadline (June–September)',
      'If applying for Fall cohort: note Spring application deadline (November–February)',
    ],
  },
  {
    name: 'CBU Nursing — 4-Year Plan: Junior Year (BSN Year 1)',
    sort_order: 311,
    items: [
      'Receive acceptance letter and confirm enrollment in BSN program',
      'Complete all required onboarding: health clearances, immunization records, CPR certification',
      'Purchase required nursing uniforms and CBU nursing ID badge',
      'Purchase required nursing equipment (stethoscope, blood pressure cuff, etc.)',
      'Complete background check and drug screening required for clinicals',
      'Register for required clinical sites and understand transportation needs',
      'Semester 1: NUR 215 — Fundamental Skills of Nursing Practice',
      'Semester 1: PathoPharm I — Pathophysiology & Pharmacology',
      'Semester 1: Begin clinical practicum hours at assigned hospital sites',
      'Semester 1: Study nursing skills lab regularly — practice hands-on skills',
      'Semester 2: PathoPharm II — Advanced Pathophysiology & Pharmacology',
      'Semester 2: NUR 325 or equivalent clinical rotation course',
      'Semester 2: Continue accumulating clinical hours (BRN mandated)',
      'Attend CBU nursing simulation lab sessions and come prepared',
      'Join the National Student Nurses Association (NSNA) chapter at CBU',
      'Meet regularly with your nursing cohort study group',
      'Keep a clinical reflection log each week',
      'Monitor your GPA — a 2.7+ is typically required to continue in the program',
    ],
  },
  {
    name: 'CBU Nursing — 4-Year Plan: Senior Year (BSN Year 2)',
    sort_order: 312,
    items: [
      'Semester 3: Complete clinical rotations — Med/Surg, Pediatrics, OB',
      'Semester 3: Advanced nursing courses — community health, leadership',
      'Semester 4: Psychiatric/Mental Health nursing rotation',
      'Semester 4: Critical Care nursing rotation',
      'Semester 5: Preceptorship / senior practicum placement',
      'Semester 5: Begin NCLEX-RN preparation (ATI, Hurst, or UWorld)',
      'Semester 6: Final clinical hours and comprehensive assessments',
      'Semester 6: Complete senior capstone or final nursing project',
      'Apply for California RN license via Breeze (California BRN portal)',
      'Submit final transcripts to California Board of Registered Nursing',
      'Register for NCLEX-RN through Pearson VUE',
      'Schedule NCLEX exam within 90 days of graduation',
      'Attend CBU pinning ceremony',
      'Graduate with Bachelor of Science in Nursing — Congratulations!',
      'Pass NCLEX-RN — you are now a Registered Nurse!',
      'Update resume and LinkedIn with BSN and RN credentials',
      'Begin job search — target local hospitals, CBU career fairs, and NurseRecruiter.com',
      'Thank your professors, clinical supervisors, and everyone who supported you',
    ],
  },

  // ── 4.5-YEAR PLAN ─────────────────────────────────────────────────────────
  {
    name: 'CBU Nursing — 4.5-Year Plan: Sophomore Year',
    sort_order: 320,
    items: [
      'Fall: Enroll in BIO 163 / 163L (Human Anatomy & Physiology II + Lab)',
      'Fall: Enroll in CHE 112 / 112L (Organic & Biochemistry + Lab)',
      'Fall: Complete general education requirements (social science, communication)',
      'Fall: Maintain cumulative GPA 3.0+ and science GPA 2.8+',
      'Fall: Explore getting CNA certified this year',
      'Spring: Enroll in BIO 205 / 205L (Human Microbiology + Lab)',
      'Spring: Complete remaining general education requirements',
      'Spring: Begin TEAS study prep — 3 months of preparation recommended',
      'Spring: Continue hospital or clinic volunteering',
      'Spring: Meet with nursing advisor to confirm remaining prereqs needed',
      'Identify which prerequisite(s) you still need to complete in the fall of junior year',
    ],
  },
  {
    name: 'CBU Nursing — 4.5-Year Plan: Junior Year (Apply & Transition)',
    sort_order: 321,
    items: [
      'Fall: Complete any remaining prerequisite courses (if not all done in sophomore year)',
      'Fall: Take the TEAS exam — aim for 75%+ composite score',
      'Fall: Open and begin your NursingCAS application',
      'Fall: Request letters of recommendation from science faculty',
      'Fall: Write your nursing personal statement',
      'Fall: Submit BSN application before deadline (June–September for Spring cohort)',
      'Fall: Submit all official transcripts through NursingCAS',
      'Fall: Verify your cumulative GPA is 3.0+ and science GPA is 2.8+',
      'Spring: Receive acceptance and complete BSN onboarding requirements',
      'Spring: Obtain CPR/BLS certification (required before clinicals)',
      'Spring: Complete health clearances, immunizations, background check, drug screen',
      'Spring: Purchase nursing uniforms, stethoscope, and required equipment',
      'Spring: Begin BSN Semester 1 — Fundamental Skills of Nursing Practice',
      'Spring: Begin clinical practicum at assigned hospital sites',
      'Spring: PathoPharm I — Pathophysiology & Pharmacology',
      'Connect with your nursing cohort — these are your people for the next 3 semesters',
    ],
  },
  {
    name: 'CBU Nursing — 4.5-Year Plan: Years 4–4.5 (BSN Program)',
    sort_order: 322,
    items: [
      'Semester 2: PathoPharm II, clinical rotations continue',
      'Semester 2: NUR 325 — Nursing Services for Childbearing Family',
      'Semester 3: Med/Surg, Pediatrics, Community Health rotations',
      'Semester 3: Leadership and management in nursing coursework',
      'Semester 4: Psychiatric/Mental Health nursing rotation',
      'Semester 4: Critical Care nursing rotation',
      'Semester 5: Senior preceptorship / advanced clinical placement',
      'Semester 5: Begin NCLEX-RN prep (ATI, Hurst, or UWorld resources)',
      'Semester 6: Final clinical hours and comprehensive exit assessments',
      'Semester 6: Complete senior capstone or nursing project',
      'Apply for California RN license through Breeze (California BRN)',
      'Register for NCLEX-RN through Pearson VUE',
      'Schedule and pass NCLEX-RN exam',
      'Attend CBU pinning ceremony',
      'Graduate with BSN — you made it!',
      'Begin nursing job search',
    ],
  },

  // ── 5-YEAR PLAN ───────────────────────────────────────────────────────────
  {
    name: 'CBU Nursing — 5-Year Plan: Sophomore Year',
    sort_order: 330,
    items: [
      'Fall: Enroll in BIO 163 / 163L (Human Anatomy & Physiology II + Lab)',
      'Fall: Focus on strong performance in science courses — no rushing',
      'Fall: Complete general education requirements (social sciences, humanities)',
      'Fall: Maintain GPA 3.0+ cumulative and 2.8+ science',
      'Spring: Enroll in CHE 112 / 112L (Organic & Biochemistry + Lab)',
      'Spring: Take advantage of tutoring and professor office hours',
      'Spring: Begin hospital volunteering if not already started',
      'Spring: Review TEAS exam materials informally — build familiarity',
      'This plan gives you more time — use it to build a stronger GPA and application',
      'Consider retaking any science course with a grade below B to improve science GPA',
    ],
  },
  {
    name: 'CBU Nursing — 5-Year Plan: Junior Year (Finish Prerequisites)',
    sort_order: 331,
    items: [
      'Fall: Enroll in BIO 205 / 205L (Human Microbiology + Lab)',
      'Fall: Complete any remaining general education requirements',
      'Fall: Earn CNA certification if not yet completed',
      'Fall: Begin serious TEAS exam preparation — schedule exam for Spring',
      'Fall: Meet with nursing advisor to confirm your application timeline',
      'Spring: Take the TEAS exam — aim for 75%+ (retake within 30 days if needed)',
      'Spring: Open and complete NursingCAS application',
      'Spring: Request letters of recommendation from science professors',
      'Spring: Write your nursing personal statement essay',
      'Spring: Submit BSN application for Fall cohort (deadline November–February)',
      'Spring: Submit all transcripts and supporting documents',
      'Spring: Verify cumulative GPA 3.0+ and science GPA 2.8+',
      'Spring: If not accepted, review feedback and plan to reapply — many students apply twice',
    ],
  },
  {
    name: 'CBU Nursing — 5-Year Plan: Year 4 (BSN Program Begins)',
    sort_order: 332,
    items: [
      'Receive acceptance and complete all BSN onboarding requirements',
      'Obtain CPR/BLS certification',
      'Complete health clearances, immunizations, background check, drug screen',
      'Purchase nursing uniforms, CBU nursing badge, and required equipment',
      'Semester 1 (Fall): NUR 215 — Fundamental Skills of Nursing Practice',
      'Semester 1 (Fall): PathoPharm I',
      'Semester 1 (Fall): Begin clinical practicum hours',
      'Semester 2 (Spring): PathoPharm II',
      'Semester 2 (Spring): NUR 325 — Childbearing Family clinical rotation',
      'Semester 2 (Spring): Continue clinical hours',
      'Semester 3 (Fall): Med/Surg and specialty clinical rotations',
      'Semester 3 (Fall): Leadership and community health coursework',
      'Keep a consistent weekly study and clinical review schedule',
      'Connect with your cohort — peer support is essential in nursing school',
    ],
  },
  {
    name: 'CBU Nursing — 5-Year Plan: Year 5 (BSN Final Year)',
    sort_order: 333,
    items: [
      'Semester 4: Psychiatric/Mental Health nursing rotation',
      'Semester 4: Critical Care nursing rotation',
      'Semester 5: Senior preceptorship — advanced clinical placement',
      'Semester 5: Begin NCLEX-RN preparation (ATI, Hurst, or UWorld)',
      'Semester 5: Complete nursing leadership project or capstone',
      'Semester 6: Final clinical hours and comprehensive assessments',
      'Semester 6: Complete all degree and program requirements for graduation',
      'Apply for California RN license via Breeze (California BRN portal)',
      'Submit final official transcripts to California BRN',
      'Register for NCLEX-RN through Pearson VUE',
      'Schedule NCLEX exam within 90 days of graduation',
      'Pass NCLEX-RN — you are officially a Registered Nurse!',
      'Attend CBU pinning ceremony',
      'Graduate with Bachelor of Science in Nursing',
      'Update resume, LinkedIn, and begin nursing job search',
    ],
  },

  // ── SHARED: TEAS Prep & Application ───────────────────────────────────────
  {
    name: 'CBU Nursing — TEAS Prep & BSN Application',
    sort_order: 340,
    items: [
      'Purchase the official ATI TEAS Study Manual (most current edition)',
      'Take a full-length TEAS practice test to get your baseline score',
      'Study TEAS Reading section — Reading passages, inferences, and text structure',
      'Study TEAS Mathematics — Numbers, algebra, measurement, and data interpretation',
      'Study TEAS Science — Human anatomy, life and physical sciences, scientific reasoning',
      'Study TEAS English — Grammar, vocabulary, spelling, and sentence structure',
      'Use Khan Academy to strengthen any weak math or science areas',
      'Take at least 3 full-length TEAS practice tests before exam day',
      'Schedule your TEAS exam through ATI Testing — aim for score of 75%+',
      'Know the rules: you may take the TEAS up to 3 times per application cycle',
      'Wait 30 days between each TEAS attempt',
      'TEAS score must be from within 6 months of the application deadline',
      'Create your NursingCAS account at nursingcas.org early',
      'Gather all official transcripts and have them sent to NursingCAS',
      'Request 2–3 letters of recommendation from science professors or supervisors',
      'Write a compelling personal statement — why nursing, why CBU, your calling',
      'Document all healthcare experience: volunteering, CNA work, shadowing hours',
      'Submit application well before the deadline — late applications are not reviewed',
      'Fall cohort deadline: applications open November, close in February',
      'Spring cohort deadline: applications open June, close in September',
      'After submitting, check your NursingCAS portal regularly for status updates',
      'If waitlisted or not accepted, contact nursing@calbaptist.edu for feedback',
      'If not accepted first time, strengthen GPA, retake TEAS, add healthcare hours, and reapply',
    ],
  },

  // ── SHARED: BSN Program & Clinicals ───────────────────────────────────────
  {
    name: 'CBU Nursing — BSN Clinical Requirements & Skills',
    sort_order: 341,
    items: [
      'Obtain CPR/BLS certification (American Heart Association — required)',
      'Complete all immunizations: Hep B, Tdap, MMR, Varicella, TB test, annual flu shot',
      'Complete HIPAA and bloodborne pathogen training',
      'Complete background check and drug screening (required before first clinical)',
      'Purchase navy blue CBU nursing scrubs and clinical supplies',
      'Purchase stethoscope (Littmann Classic III recommended), blood pressure cuff, pen light',
      'Download required clinical apps (Epocrates, NursingCentral, or CBU-approved apps)',
      'Review clinical site rules: no phones, proper attire, professional conduct',
      'Keep a weekly clinical reflection journal',
      'Practice nursing skills in simulation lab outside of required class hours',
      'Study pharmacology flashcards daily — medications are tested continuously',
      'Complete all ATI assessments on time — scores impact program standing',
      'Maintain minimum required GPA to remain in the nursing program',
      'Notify clinical coordinator immediately of any health changes before rotations',
      'Rotate through: Medical-Surgical, Pediatrics, OB/Maternity, Psychiatric, Community Health, ICU',
      'Document clinical hours accurately in required tracking system',
      'Attend all simulation lab sessions — attendance is mandatory',
    ],
  },

  // ── SHARED: Graduation & Licensure ────────────────────────────────────────
  {
    name: 'CBU Nursing — NCLEX & Graduation',
    sort_order: 342,
    items: [
      'Begin NCLEX-RN prep at least 3 months before graduation',
      'Use UWorld, Hurst Review, or ATI Comprehensive NCLEX review',
      'Complete at least 2,000 NCLEX practice questions',
      'Review priority, delegation, and safety questions — heavily tested on NCLEX',
      'Focus on "select all that apply" (SATA) questions and pharmacology',
      'Study the NCLEX Next Generation format — includes case studies and new question types',
      'Apply for California RN licensure through Breeze (breeze.ca.gov)',
      'Submit official final transcripts to California Board of Registered Nursing (BRN)',
      'Complete the California BRN application checklist fully before submitting',
      'Pay California BRN application fee',
      'Register for NCLEX-RN through Pearson VUE after receiving Authorization to Test (ATT)',
      'Schedule NCLEX within 90 days of receiving ATT',
      'Apply for NCLEX at a Pearson VUE testing center near Riverside',
      'On exam day: bring valid ID, arrive early, no phones or notes allowed',
      'After passing NCLEX: verify license on California BRN Breeze portal',
      'Apply to nursing jobs — acute care hospitals, clinics, schools, and specialty units',
      'Attend CBU Pinning Ceremony — a milestone to celebrate with family',
      'Walk in CBU Commencement — receive your Bachelor of Science in Nursing',
      'Update LinkedIn, resume, and all professional profiles with RN, BSN credentials',
      'Thank God, your family, professors, and everyone who walked this journey with you',
    ],
  },
];
