export interface MovingTaskCategory {
  name: string;
  sort_order: number;
  items: string[];
}

export const MOVING_TASK_LIBRARY_SEED: MovingTaskCategory[] = [
  {
    name: 'Moving — 6 Months Out',
    sort_order: 200,
    items: [
      'Decide on moving date and start researching neighborhoods',
      'Set a total moving budget',
      'Research and compare moving companies or truck rentals',
      'Declutter every room — donate, sell, or discard',
      'Host a garage sale or list items on Facebook Marketplace',
      'Start a moving binder or folder for paperwork',
      'Research schools, churches, and community resources in new area',
      'Notify employer of planned relocation if needed',
      'Research cost of living in new city or neighborhood',
      'Begin saving for moving expenses and deposits',
      'Order a free credit report to prepare for new lease or mortgage',
      'Research storage unit options if needed',
    ],
  },
  {
    name: 'Moving — 3 Months Out',
    sort_order: 201,
    items: [
      'Book moving company or reserve rental truck',
      'Confirm moving date with landlord or real estate agent',
      'Begin collecting moving boxes and packing supplies',
      'Sort through closets, attic, garage, and basement',
      'Donate or dispose of anything you won\'t bring to the new home',
      'Research and compare homeowner\'s or renter\'s insurance quotes',
      'Request records from doctors, dentists, and specialists',
      'Request school records for children',
      'Notify employer of new address (HR, payroll)',
      'Research utility providers in new area (electric, gas, internet)',
      'Measure rooms in new home to plan furniture placement',
      'Decide what furniture to keep, sell, or replace',
    ],
  },
  {
    name: 'Moving — 2 Months Out',
    sort_order: 202,
    items: [
      'Start packing non-essential items (off-season clothes, décor, books)',
      'Label all boxes clearly with room and contents',
      'Photograph valuables for insurance purposes',
      'Arrange transfer of prescriptions to pharmacy in new area',
      'Notify bank and credit card companies of address change',
      'Update address with employer payroll department',
      'Contact insurance companies (home, auto, life) about address change',
      'Research and contact internet and cable providers for new address',
      'Look into parking or elevator reservations at new building',
      'Arrange childcare or pet care for moving day',
      'Plan what you\'ll need access to on moving day (pack last)',
      'Confirm dates with any specialty movers (piano, art, etc.)',
    ],
  },
  {
    name: 'Moving — 1 Month Out',
    sort_order: 203,
    items: [
      'File official change of address with USPS',
      'Notify friends and family of new address',
      'Update address on Amazon, online shopping accounts',
      'Cancel or transfer local memberships (gym, library, clubs)',
      'Arrange utilities shut-off at current home',
      'Schedule utilities turn-on at new home',
      'Transfer or cancel home security monitoring',
      'Return borrowed items to neighbors, friends, or library',
      'Collect items you have lent out',
      'Dispose of hazardous materials (paint, chemicals) properly',
      'Use up perishable food from freezer and pantry',
      'Confirm moving company booking and get written confirmation',
      'Pack a "first night" box with essentials for new home',
      'Take photos of current home for any security deposit dispute',
    ],
  },
  {
    name: 'Moving — 2 Weeks Out',
    sort_order: 204,
    items: [
      'Confirm moving truck or company final details',
      'Pack majority of house — leave only daily essentials',
      'Clean out and defrost refrigerator and freezer',
      'Disassemble large furniture that needs it',
      'Gather all keys, garage remotes, and access cards',
      'Back up computer and important digital files',
      'Pack valuables and important documents in personal bag to carry yourself',
      'Notify subscription boxes of new address (Amazon, Hello Fresh, etc.)',
      'Update voter registration with new address',
      'Set up mail forwarding start date to coincide with move date',
      'Arrange travel plans for moving day (hotel if long distance)',
      'Charge all electronics and pack chargers together',
    ],
  },
  {
    name: 'Moving — 1 Week Out',
    sort_order: 205,
    items: [
      'Confirm all logistics: time, address, contacts for moving day',
      'Finish packing all remaining rooms',
      'Label "Load Last / Unload First" box for essentials',
      'Pack cleaning supplies separately for final clean',
      'Gather and pack all pet supplies, food, and carriers',
      'Prepare tip cash for movers',
      'Get snacks and water ready for moving day',
      'Do final walkthrough of each room',
      'Confirm keys or access to new home for moving day',
      'Charge phone and portable battery pack',
      'Make sure children\'s favorite items and comfort items are accessible',
      'Confirm pet boarding or care for moving day',
    ],
  },
  {
    name: 'Moving Day',
    sort_order: 206,
    items: [
      'Do a final walkthrough of every room, closet, and cabinet',
      'Check attic, basement, garage, and outdoor areas',
      'Check inside all appliances (washer, dryer, dishwasher, oven)',
      'Take meter readings for gas and electric before leaving',
      'Leave keys, garage remotes, and mailbox keys for new owners or landlord',
      'Take photos of old home in move-out condition',
      'Direct movers on where items go in new home',
      'Check all boxes and furniture for damage before signing off',
      'Test all utilities at new home (water, electric, gas, heat/AC)',
      'Locate circuit breaker and main water shut-off at new home',
      'Set up beds first so everyone can sleep comfortably that night',
      'Order dinner — don\'t try to cook on moving day',
      'Do a safety walk of new home with family',
    ],
  },
  {
    name: 'Moving — First Week in New Home',
    sort_order: 207,
    items: [
      'Unpack kitchen and bedrooms first',
      'Set up children\'s rooms to help them feel at home',
      'Locate nearest hospital, urgent care, pharmacy, and grocery store',
      'Get new home keys copied for family members',
      'Change locks or rekey all doors',
      'Test all smoke detectors and carbon monoxide detectors',
      'Replace furnace filters',
      'Check for any issues and document for landlord or warranty',
      'Introduce yourself to neighbors',
      'Find nearest gas station, grocery store, and church',
      'Update driver\'s license address (required within 30 days in most states)',
      'Update vehicle registration with new address',
      'Set up new internet and test connection',
      'Hang up a cross or Scripture for your new home blessing',
    ],
  },
  {
    name: 'Moving — First Month in New Home',
    sort_order: 208,
    items: [
      'Establish new doctor, dentist, and specialist relationships',
      'Enroll children in school',
      'Find a local church home',
      'Get a library card',
      'Update address on all remaining accounts and subscriptions',
      'Update address on vehicle and life insurance',
      'Review and update estate documents if needed (will, trust, POA)',
      'Set up automatic bill pay for new utilities',
      'Explore the new neighborhood on foot or by car',
      'Connect with community groups, playgroups, or mom groups',
      'Hang art and personalize your space',
      'Deep clean any areas not cleaned before move-in',
      'Confirm mail forwarding is working correctly',
      'Send new address announcement to extended family and friends',
    ],
  },
];
